### ISSUE TITLE
Add example values file for testnet

### ISSUE THREAD

**Issue by andrenarchy** [satoshipay/stellar-helm-charts#6]

**Comment by todkap** [comment]
I was using these for my local testing. 

**Docker-Compose**
https://github.com/todkap/stellar-testnet/blob/master/docker/docker-compose.yml#L29-L57

**K8 Deployment**
https://github.com/todkap/stellar-testnet/blob/k8-deploy-postgres-helmchart/kubernetes/stellar-core-deployment.yaml#L30-L49

**Comment by andrenarchy** [comment]
Also see the updated README.
